config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'games#home'
  get 'new', to: 'games#new'
  post 'score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'

class GamesController < ApplicationController
  def home
  end

  def new
    @letters = []
    2.times { @letters << %w[A E I O U].sample }
    9.times { @letters << ('A'..'Z').to_a.sample }
  end

  def score
    @guess = params[:guess].upcase
    grid = params[:grid].scan(/\w/)
    guess_letters = @guess.split('')
    ok_letters = 0

    guess_letters.each do |guess_letter|
      grid.each_with_index do |grid_letter, grid_index|
        if grid_letter == guess_letter
          grid.delete_at(grid_index)
          ok_letters += 1
          break
        else
          next
        end
      end
    end

    if @guess.length == ok_letters
      filepath = "https://wagon-dictionary.herokuapp.com/#{@guess}"
      serialized_dictionary = URI.open(filepath).read
      dictionary_response = JSON.parse(serialized_dictionary)
      if dictionary_response['found'] == true
        score = dictionary_response['length'] * 4
        @message = "Congrats ! Le mot #{@guess} existe dans la grid ! ✅  Votre score est de #{score} points!"
      else
        @message = "Le mot #{@guess} n'est pas anglais!"
      end
    else
      @message = "Dommage ! Le mot n'existe pas dans la grid ❌"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/home.html.erb
<h1>Home page</h1>
<%= link_to "New Game", new_path %>
<%= link_to "Score Page", score_path %>

app/views/games/new.html.erb
<h1>Here are your new letters:</h1>

<ul>
<% @letters.each do |letter| %>
  <li><%= letter %></li>
<% end %>
</ul>

<form action="/score" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<input type="text" name="guess">
<input type="submit" value="Try this word!">
<input name="grid" type="hidden" value="<%= @letters%>" />
</form>

app/views/games/score.html.erb
<h1>Result</h1>

<p> <%= @message %> </p>

<%= link_to 'Play again', new_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>